DiscordMessage: "&dJoin our Discord server: https://discord.gg/yourServerLink\n&eBe sure to read the rules!"
StoreMessage: "&dStore&8: &fhttps://store.example.com"
VoteMessage: "&dVote Here&8: &fhttps://vote1.example.com"