name: CustomCommands
version: '1.0'
main: xyz.nexusservices.customCommands.CustomCommands
api-version: '1.20'
authors: [ FroostySnoowman, Someone ]
commands:
    discord:
        description: Displays the server's Discord link
        usage: /discord
    store:
        description: Displays the server's Store link
        usage: /store
    vote:
        description: Displays the server's Vote link(s)
        usage: /vote